FROM python:3.11.11 AS flask

WORKDIR /App

COPY requirements.txt /App/requirements.txt
RUN /App/venv/bin/pip install --no-cache-dir -r /App/requirements.txt

COPY . /App  

EXPOSE 5001  

ENTRYPOINT ["python", "app.py"]
