version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flasksbackup-server
    networks:
      - jenkinsbackup-net
    ports:
      - "5001:5001"
    restart: always

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkinsbackup-server
    networks:
      - jenkinsbackup-net
    ports:
      - "8081:8081"
      - "50001:50001"
    volumes:
      - jenkinsbackup-vol:/var/jenkins_home
    restart: always

networks:
  jenkinsbackup-net:
    driver: bridge

volumes:
  jenkinsbackup-vol:

group_add:
  - 988
