FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    awscli \
    docker.io \
    sudo

RUN usermod -aG docker jenkins  

VOLUME ["/var/jenkins_home"]

EXPOSE 8080 50000

USER jenkins  

ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/jenkins/jenkins.war"]
