# Stage 1: Build Stage
FROM jenkins/jenkins:lts-jdk17 AS jenkins-build

USER root

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    awscli \
    docker.io \
    sudo

RUN usermod -aG docker jenkins  

# Stage 2: Runtime Stage
FROM jenkins/jenkins:lts-jdk17 AS jenkins-runtime

USER jenkins

COPY --from=jenkins-build /usr/share/jenkins /usr/share/jenkins
COPY --from=jenkins-build /usr/bin /usr/bin

EXPOSE 8081 50001

ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/jenkins/jenkins.war"]
