version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
      container_name: jenkinsbackup-server
      networks:
      - jenkinsbackup-net    
    ports:
      - "8081:8081"
      - "50001:50001"
    volumes:
      - jenkinsbackup-vol:/var/jenkins_home
    restart: always
    environment:
      - JAVA_OPTS="-Xmx2g -Xms512m"
    group_add:
      - 988
volumes:
  jenkins_home:

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flasksbackup-server
    networks:
      - jenkinsbackup-net
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    restart: always
    depends_on:
      - jenkins

networks:
  jenkinsbackup-net:
    driver: bridge

volumes:
  jenkinsbackup-vol:
    driver: local
